org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1
mod_id=kaleidoscope_world_liquor
mod_name=Kaleidoscope World Liquor
mod_license=MIT
mod_version=1.0.3-beta3-forge+mc1.20.1
mod_group_id=com.bmt.kaleidoscope_world_liquor
mod_authors=BmtUltra,Chenjdy,bfxm
mod_description=It adds a variety of well-known real-world wines and spirits,such as Bombay Sapphire Gin, Smirnoff Vodka, Spirytus Vodka, Moutai, Bacardi White Rum, and many other classic liquors.